# -*- coding: utf-8 -*-
"""BuoiHocDauTien

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KECtANW-nTuoLWFkgpfEj532WonOe6BA
"""

#Ví dụ chương 1
print('Albert Einstein đã từng nói: Một người không bao giờ mắc sai lầm không bao giờ thử bất kì điều gì mới.')

#Ví dụ chương 1
#tinh tong hai so nguyen
so1= int(input('Nhap so thu nhat: '))
so2= int(input('Nhap so thu hai: '))
#tinh tong
tong=so1+so2
#hien ket qua
print("Tong hai so la: ",tong)

#Ví dụ chương 1
import math
number=16
square_root=math.sqrt(number)
print("Căn bậc hai của", number," là ",square_root)

#Ví dụ chương 1
question='What is the meaning of Life, the Universe, and Everything?'
answer=42

#Ví dụ chương 1
question='What is your quest?'
answer='To seek the holy grail.'

#Bài tập 4
print('Chao cac ban')

#Bài tập 5
print('Nguyen Thi Truc Ly')

#Bài tập 6
print('Mình về mình có nhớ ta?\nMười lăm năm ấy thiết tha mặn nồng.\nMình về mình có nhớ không?\nNhìn cây nhớ núi, nhìn sông nhớ nguồn.')

#Bài tập 7
import sys
if len(sys.argv)>1:
  print('Chuỗi bạn vừa nhập: ',sys.argv[1])
else:
  print("Vui lòng nhập một chuỗi kí tự!")

#Bài tập 9
rong=9
cao=4
for i in range(cao):
  print('*'*rong)

#Bài tập 8
print('****\n*  *\n*  *\n****')

#Bài tập 10
def cay_thong():
    chieu_rong = 9   # độ rộng tối đa
    tang = [1, 3, 5, 3, 5, 9, 1, 1]  # số sao mỗi dòng

    for sao in tang:
        khoang_trang = (chieu_rong - sao) // 2
        print(" " * khoang_trang + "*" * sao)

cay_thong()