# -*- coding: utf-8 -*-
"""BuoiHocDauTien

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KECtANW-nTuoLWFkgpfEj532WonOe6BA
"""

print('Albert Einstein đã từng nói: Một người không bao giờ mắc sai lầm không bao giờ thử bất kì điều gì mới.')

#tinh tong hai so nguyen
so1= int(input('Nhap so thu nhat: '))
so2= int(input('3Nhap so thu hai: '))
#tinh tong
tong=so1+so2
#hien ket qua
print("Tong hai so la: ",tong)

import math
number=16
square_root=math.sqrt(number)
print("Căn bậc hai của", number," là ",square_root)

print('Chao cac ban')

print('Nguyen Thi Truc Ly')

print('Mình về mình có nhớ ta?\nMười lăm năm ấy thiết tha mặn nồng.\nMình về mình có nhớ không?\nNhìn cây nhớ núi, nhìn sông nhớ nguồn.')

a='son tung mtp'
print(a)

rong=9
cao=4
for i in range(cao):
  print('*'*rong)

print('****\n*  *\n*  *\n****')

def cay_thong():
    chieu_rong = 9   # độ rộng tối đa
    tang = [1, 3, 5, 3, 5, 9, 1, 1]  # số sao mỗi dòng

    for sao in tang:
        khoang_trang = (chieu_rong - sao) // 2
        print(" " * khoang_trang + "*" * sao)

cay_thong()